repos:
  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
  #  - repo: local
  #    hooks:
  #      - id: pylint
  #        name: pylint
  #        entry: poetry run pylint samudra/
  #        language: system
  #        always_run: true
  #        pass_filenames: false
#  - repo: https://github.com/python-poetry/poetry
#    rev: 1.2.0
#    hooks:
#      - id: poetry-check
#      - id: poetry-lock
#      - id: poetry-export
#        name: create requirements with mysql
#        args: [ "-o", "requirements.txt", "--extras", "mysql", "--without-hashes" ]